# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'ios-kotlin-mpp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-kotlin-mpp
  pod 'kotlin_mpp', :path => '../../kotlin-mpp'
end
